### PR TITLE
Support for Chartboost 9.0.0

### PR DESCRIPTION
**Pull request by daniel-barros**
Updated adapters to use new APIs and remove usage of old APIs.

### CODE REVIEW

**Comment by arnaumartifont** [comment]
do you know if we need to update the AppLovinMediationChartboostAdapter.podspec?

**Review by arnaumartifont — APPROVED** [review]
looks good 👍

**Review by arnaumartifont — CHANGES_REQUESTED** [review]
code wise all good, the project ChartboostAdapter.xcodeproj is outdated?
dropped the dependencies there ChartboostSDK.xcframework & AppLovinSDK.xcframework.

failed to build and saw that is missing the link part of these dependencies, and there was only listed  the outdated .framework from AppLovin.
Screenshot 2022-05-27 at 11 33 55

 and btw, no clear instructions from them how to build the Adapter. 
how do we build the .framework instead of the static lib?
I might be missing something, other adapters have the same structure.

**Review by arnaumartifont — DISMISSED** [review]

**Comment by daniel-barros** [comment]
> do you know if we need to update the AppLovinMediationChartboostAdapter.podspec?

Won't hurt. Just did it.

**Comment by daniel-barros** [comment]
> code wise all good, the project ChartboostAdapter.xcodeproj is outdated? dropped the dependencies there ChartboostSDK.xcframework & AppLovinSDK.xcframework.
> 
> failed to build and saw that is missing the link part of these dependencies, and there was only listed the outdated .framework from AppLovin. Screenshot 2022-05-27 at 11 33 55
> 
> and btw, no clear instructions from them how to build the Adapter. how do we build the .framework instead of the static lib? I might be missing something, other adapters have the same structure.

I suspect they have some non-open source scripts that build the framework adapters.
What I did was adding a new framework target and include the .m file in it. Very quick. I attached it in the ticket as a zip.
I think whatever changes need to be applied to the project AppLovin will have to take care of it.

**Review by arnaumartifont — APPROVED** [review]

**Pull request closed without merging**
